"""Native-free affine SynthMorph registration to the MNI305 Talairach template."""

from pathlib import Path
import argparse

import numpy as np
import surfa as sf
import torch

from fnit.synthmorph import SynthMorph


def _matmul_float32(left: np.ndarray, right: np.ndarray) -> np.ndarray:
    """FreeSurfer MatrixMultiply accumulates each entry in float32 order."""
    left, right = np.asarray(left, np.float32), np.asarray(right, np.float32)
    output = np.zeros((4, 4), np.float32)
    for row in range(4):
        for col in range(4):
            value = np.float32(0)
            for index in range(4):
                value = np.float32(value + np.float32(left[row, index] * right[index, col]))
            output[row, col] = value
    return output


def talairach_matrix(affine: sf.Affine) -> np.ndarray:
    """Replay the RAS→voxel→RAS conversion used by ``rca-talairach``."""
    world = affine.convert(space="world")
    source = np.asarray(world.source.vox2world.matrix, np.float32)
    target = np.asarray(world.target.vox2world.matrix, np.float32)
    source_inverse = np.linalg.inv(source.astype(np.float64)).astype(np.float32)
    target_inverse = np.linalg.inv(target.astype(np.float64)).astype(np.float32)
    voxel = _matmul_float32(target_inverse, _matmul_float32(world.matrix, source))
    return _matmul_float32(target, _matmul_float32(voxel, source_inverse))


def write_talairach_xfm(matrix: np.ndarray, output: str | Path) -> None:
    """Write an MNI linear XFM that FreeSurfer can read."""
    rows = np.asarray(matrix, np.float32)
    if rows.shape != (4, 4) or not np.isfinite(rows).all():
        raise ValueError("talairach matrix must be finite and 4x4")
    lines = ["MNI Transform File", "%Generated by fnit", "",
             "Transform_Type = Linear;", "Linear_Transform ="]
    for index in range(3):
        line = " ".join(f"{float(value):13.8f}" for value in rows[index])
        lines.append(line + (" ;" if index == 2 else ""))
    path = Path(output)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


def register_talairach(moving: str | Path, template: str | Path,
                       weights: str | Path, output_xfm: str | Path,
                       output_lta: str | Path | None = None,
                       device: str = "cpu", threads: int = 4) -> np.ndarray:
    """Run the archived affine-only stage without FreeSurfer executables."""
    torch.set_num_threads(threads)
    model = SynthMorph(weights=weights, device=device, model="affine", extent=256)
    result = model(moving, template)
    if output_lta is not None:
        path = Path(output_lta)
        path.parent.mkdir(parents=True, exist_ok=True)
        result.transform.save(str(path))
    matrix = talairach_matrix(result.transform)
    write_talairach_xfm(matrix, output_xfm)
    return matrix


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("moving", type=Path, help="brain-extracted synthstrip.mgz")
    parser.add_argument("template", type=Path, help="mni305.cor.stripped.mgz")
    parser.add_argument("--weights", required=True, type=Path)
    parser.add_argument("--xfm", required=True, type=Path)
    parser.add_argument("--lta", type=Path)
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--threads", type=int, default=4)
    args = parser.parse_args()
    register_talairach(args.moving, args.template, args.weights,
                       args.xfm, args.lta, args.device, args.threads)


if __name__ == "__main__":
    main()
