"""Pin the float32 determinant used by FreeSurfer's global eTIV measure."""

import pytest

from fnit.recon_all.estimated_tiv import estimate_tiv


def test_estimate_tiv_matches_native_six_decimals(tmp_path):
    xfm = tmp_path / "talairach.xfm"
    xfm.write_text("""MNI Transform File
%Generated by lta_convert src none dst none

Transform_Type = Linear;
Linear_Transform =
   1.08495569    0.14990307    0.07729009    2.98810577
  -0.15601470    1.02990830    0.33936635  -25.03691864
  -0.04544587   -0.29234937    1.20471454   39.67505646 ;
""")
    assert f"{estimate_tiv(xfm):.6f}" == "1310266.152503"


def test_estimate_tiv_rejects_missing_matrix(tmp_path):
    xfm = tmp_path / "talairach.xfm"
    xfm.write_text("MNI Transform File\nTransform_Type = Linear;\n")
    with pytest.raises(ValueError, match="Linear_Transform"):
        estimate_tiv(xfm)
